### ISSUE TITLE
IS_OFFLINE has been removed

### ISSUE THREAD

**Issue by dhruvbhatia** [99xt/serverless-dynamodb-client#15]
The plugin doesn't detect local environments anymore because the [`IS_OFFLINE` ](https://github.com/99xt/serverless-dynamodb-client/blob/b0e4179c5a349df145dbb8c84040ea0b2f1e9ef2/index.js#L9)flag has been removed. See https://github.com/dherault/serverless-offline/issues/768#issue-476929826

**Comment by KingDarBoja** [comment]
We need to rely on something like [serverless-dotenv-plugin](https://github.com/colynb/serverless-dotenv-plugin) in the meantime.

**Comment by adimoraret** [comment]
so the only workaround for now is to manually set the `process.env.IS_OFFLINE` to `true` before running ` sls offline start` ?

**Comment by KingDarBoja** [comment]
@adimoraret Yes, it is required. I think there is some work in progress at this [serverless-dotenv-plugin PR](https://github.com/colynb/serverless-dotenv-plugin/pull/55) to detect a shared env file with basic env variables like `offline` before starting any other serverless plugin.
